FROM python:3

RUN mkdir -p /app
WORKDIR /app

COPY ./src/requirements.txt /app/requirements.txt

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --upgrade pip setuptools wheel                                                                                                                                                                                                
RUN python3 -m pip install -r requirements.txt 



COPY ./src/ /app/

ENV FLASK_APP=app.py
EXPOSE 5000


CMD flask run -h 0.0.0.0 -p 5000